# Generated by Django 2.0.1 on 2018-01-18 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0007_space_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='space',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Space', to='space.Space'),
        ),
    ]
