# Generated by Django 2.0.1 on 2018-01-18 14:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0008_auto_20180118_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='space',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Space', to='space.Space'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='space',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Space_User', to=settings.AUTH_USER_MODEL),
        ),
    ]
