# Generated by Django 2.0.1 on 2018-01-17 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0004_auto_20180117_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occupant',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Room', to='space.Room'),
        ),
        migrations.AlterField(
            model_name='room',
            name='space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Space', to='space.Space'),
        ),
    ]
