# Generated by Django 2.0.1 on 2018-01-18 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0005_auto_20180117_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occupant',
            name='entry_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='occupant',
            name='exit_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
