# Generated by Django 2.0.1 on 2018-01-18 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0010_auto_20180118_1406'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='space',
            name='owner',
        ),
    ]
